-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-13 13:47:19 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cazari 
    ( 
     id_cazare   NUMBER (8)  NOT NULL , 
     CNP         VARCHAR2 (13)  NOT NULL , 
     nume_cazare VARCHAR2 (30)  NOT NULL , 
     pret24h     NUMBER (6,2)  NOT NULL , 
     adresa      VARCHAR2 (200)  NOT NULL , 
     oras        VARCHAR2 (20)  NOT NULL , 
     tara        VARCHAR2 (30)  NOT NULL , 
     tip_cazare  VARCHAR2 (10) 
    ) 
    LOGGING 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_id_cazare_ck 
    CHECK (id_cazare >= 50) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_nume_cazare_ck 
    CHECK (length(nume_cazare) >= 5 and regexp_like(nume_cazare, '^[A-Za-zĂÂÎȘȚăâîșț ]+$')) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_pret_ck 
    CHECK (pret24h >= 50.00) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_adresa_ck 
    CHECK (length(adresa) >= 10) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_oras_ck 
    CHECK (length(oras) >= 4 and regexp_like(oras, '^[A-Za-zĂÂÎȘȚăâîșț ]+$')) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_tara_ck 
    CHECK (length(tara) >= 2 and regexp_like(tara, '^[A-Za-zĂÂÎȘȚăâîșț ]+$')) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_tip_cazare_ck 
    CHECK (tip_cazare IN ('apartament', 'hotel', 'motel', 'pensiune', 'vila')) 
;

ALTER TABLE cazari 
    ADD CONSTRAINT cazari_PK PRIMARY KEY ( id_cazare ) ;

CREATE TABLE clienti 
    ( 
     CNP         VARCHAR2 (13)  NOT NULL , 
     nume_client VARCHAR2 (30)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE clienti 
    ADD CONSTRAINT clienti_nume_client_ck 
    CHECK (length(nume_client) >= 8 and regexp_like(nume_client, '^[A-Za-zĂÂÎȘȚăâîșț -]+$')) 
;

ALTER TABLE clienti 
    ADD CONSTRAINT clienti_PK PRIMARY KEY ( CNP ) ;

CREATE TABLE persoane 
    ( 
     CNP           VARCHAR2 (13)  NOT NULL , 
     adresa_email  VARCHAR2 (60) , 
     numar_telefon VARCHAR2 (10) 
    ) 
    LOGGING 
;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_CNP_ck 
    CHECK (length(CNP) = 13 and regexp_like(CNP, '^[0-9]{13}$')) 
;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_adresa_email_ck 
    CHECK (regexp_like(adresa_email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_numar_telefon_ck 
    CHECK (length(numar_telefon) = 10) 
;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_PK PRIMARY KEY ( CNP ) ;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_adresa_email_uk UNIQUE ( adresa_email ) ;

ALTER TABLE persoane 
    ADD CONSTRAINT persoane_numar_telefon_uk UNIQUE ( numar_telefon ) ;

CREATE TABLE proprietari 
    ( 
     CNP             VARCHAR2 (13)  NOT NULL , 
     nume_proprietar VARCHAR2 (30)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE proprietari 
    ADD CONSTRAINT proprietari_nume_proprietar_ck 
    CHECK (length(nume_proprietar)  >= 8 and regexp_like(nume_proprietar, '^[A-Za-zĂÂÎȘȚăâîșț -]+$')) 
;

ALTER TABLE proprietari 
    ADD CONSTRAINT proprietari_PK PRIMARY KEY ( CNP ) ;

CREATE TABLE recenzii 
    ( 
     id_rezervare NUMBER (10)  NOT NULL , 
     continut     VARCHAR2 (2000) , 
     stele        NUMBER (1)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE recenzii 
    ADD CONSTRAINT recenzii_stele_ck 
    CHECK (stele BETWEEN 1 AND 5) 
;

ALTER TABLE recenzii 
    ADD CONSTRAINT recenzii_PK PRIMARY KEY ( id_rezervare ) ;

CREATE TABLE rezervari 
    ( 
     id_rezervare NUMBER (10)  NOT NULL , 
     CNP          VARCHAR2 (13)  NOT NULL , 
     id_cazare    NUMBER (8)  NOT NULL , 
     durata_zile  NUMBER (2)  NOT NULL , 
     data_inceput DATE  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE rezervari 
    ADD CONSTRAINT rezervari_id_rezervare_ck 
    CHECK (id_rezervare >= 2000) 
;

ALTER TABLE rezervari 
    ADD CONSTRAINT rezervari_durata_zile_ck 
    CHECK (durata_zile BETWEEN 1 AND 30) 
;

ALTER TABLE rezervari 
    ADD CONSTRAINT rezervari_PK PRIMARY KEY ( id_rezervare ) ;

ALTER TABLE rezervari 
    ADD CONSTRAINT cazari_rezervari_fk FOREIGN KEY 
    ( 
     id_cazare
    ) 
    REFERENCES cazari 
    ( 
     id_cazare
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE rezervari 
    ADD CONSTRAINT clienti_rezervari_fk FOREIGN KEY 
    ( 
     CNP
    ) 
    REFERENCES clienti 
    ( 
     CNP
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE clienti 
    ADD CONSTRAINT persoane_clienti_fk FOREIGN KEY 
    ( 
     CNP
    ) 
    REFERENCES persoane 
    ( 
     CNP
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE proprietari 
    ADD CONSTRAINT persoane_proprietari_fk FOREIGN KEY 
    ( 
     CNP
    ) 
    REFERENCES persoane 
    ( 
     CNP
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE cazari 
    ADD CONSTRAINT proprietari_cazari_fk FOREIGN KEY 
    ( 
     CNP
    ) 
    REFERENCES proprietari 
    ( 
     CNP
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE recenzii 
    ADD CONSTRAINT rezervari_recenzii_fk FOREIGN KEY 
    ( 
     id_rezervare
    ) 
    REFERENCES rezervari 
    ( 
     id_rezervare
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER trg_rezervari_BRIU 
    BEFORE INSERT OR UPDATE ON rezervari 
    FOR EACH ROW 
BEGIN
IF( :new.data_inceput <= SYSDATE )
THEN
RAISE_APPLICATION_ERROR( -20001,
'Data invalida: ' || TO_CHAR( :new.data_inceput, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
END IF;
END; 
/

CREATE SEQUENCE cazari_id_cazare_seq 
START WITH 50 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER cazari_id_cazare_trg 
BEFORE INSERT ON cazari 
FOR EACH ROW 
WHEN (NEW.id_cazare IS NULL) 
BEGIN 
    :NEW.id_cazare := cazari_id_cazare_seq.NEXTVAL; 
END;
/

CREATE SEQUENCE rezervari_id_rezervare_seq 
START WITH 2000 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER rezervari_id_rezervare_trg 
BEFORE INSERT ON rezervari 
FOR EACH ROW 
WHEN (NEW.id_rezervare IS NULL) 
BEGIN 
    :NEW.id_rezervare := rezervari_id_rezervare_seq.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
